# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hotel_search/v1/common.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.type import phone_number_pb2 as google_dot_type_dot_phone__number__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1chotel_search/v1/common.proto\x12\x0fhotel_search.v1\x1a\x1egoogle/type/phone_number.proto\"\xa6\x01\n\x05Guest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x03 \x01(\t\x12\x33\n\x0cphone_number\x18\x04 \x01(\x0b\x32\x18.google.type.PhoneNumberH\x00\x88\x01\x01\x12\x16\n\tmember_id\x18\x06 \x01(\x03H\x01\x88\x01\x01\x42\x0f\n\r_phone_numberB\x0c\n\n_member_id*V\n\x07\x41menity\x12\x12\n\x0e\x46REE_BREAKFAST\x10\x00\x12\x0e\n\nWATER_VIEW\x10\x01\x12\x10\n\x0c\x46REE_PARKING\x10\x02\x12\x15\n\x11\x46REE_CANCELLATION\x10\x03*<\n\x03\x42\x65\x64\x12\x08\n\x04TWIN\x10\x00\x12\x0b\n\x07TRUNDLE\x10\x01\x12\t\n\x05\x46UTON\x10\x02\x12\t\n\x05QUEEN\x10\x03\x12\x08\n\x04KING\x10\x04*A\n\x08\x43\x61tegory\x12\n\n\x06\x42UDGET\x10\x00\x12\x0c\n\x08STANDARD\x10\x01\x12\x0c\n\x08\x42USINESS\x10\x02\x12\r\n\tEXECUTIVE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hotel_search.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AMENITY']._serialized_start=250
  _globals['_AMENITY']._serialized_end=336
  _globals['_BED']._serialized_start=338
  _globals['_BED']._serialized_end=398
  _globals['_CATEGORY']._serialized_start=400
  _globals['_CATEGORY']._serialized_end=465
  _globals['_GUEST']._serialized_start=82
  _globals['_GUEST']._serialized_end=248
# @@protoc_insertion_point(module_scope)
