# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hotel_search/v1/hotel_search_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hotel_search.v1 import hotel_search_request_pb2 as hotel__search_dot_v1_dot_hotel__search__request__pb2
from hotel_search.v1 import hotel_search_response_pb2 as hotel__search_dot_v1_dot_hotel__search__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*hotel_search/v1/hotel_search_service.proto\x12\x0fhotel_search.v1\x1a*hotel_search/v1/hotel_search_request.proto\x1a+hotel_search/v1/hotel_search_response.proto2n\n\x12HotelSearchService\x12X\n\x0bHotelSearch\x12#.hotel_search.v1.HotelSearchRequest\x1a$.hotel_search.v1.HotelSearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hotel_search.v1.hotel_search_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOTELSEARCHSERVICE']._serialized_start=152
  _globals['_HOTELSEARCHSERVICE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
