# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hotel_search/v1/hotel_search_request.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.type import date_pb2 as google_dot_type_dot_date__pb2
from google.type import money_pb2 as google_dot_type_dot_money__pb2
from hotel_search.v1 import common_pb2 as hotel__search_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*hotel_search/v1/hotel_search_request.proto\x12\x0fhotel_search.v1\x1a\x16google/type/date.proto\x1a\x17google/type/money.proto\x1a\x1chotel_search/v1/common.proto\"\xca\x03\n\x12HotelSearchRequest\x12\x32\n\x0cuser_session\x18\x01 \x01(\x0b\x32\x1c.hotel_search.v1.UserSession\x12\x13\n\x0bguest_count\x18\x02 \x01(\r\x12(\n\rcheck_in_date\x18\x04 \x01(\x0b\x32\x11.google.type.Date\x12)\n\x0e\x63heck_out_date\x18\x05 \x01(\x0b\x32\x11.google.type.Date\x12\x18\n\x10\x63ity_of_interest\x18\x06 \x01(\t\x12\x32\n\x11max_nightly_price\x18\x07 \x01(\x0b\x32\x12.google.type.MoneyH\x00\x88\x01\x01\x12-\n\ncategories\x18\x08 \x03(\x0e\x32\x19.hotel_search.v1.Category\x12+\n\tamenities\x18\t \x03(\x0e\x32\x18.hotel_search.v1.Amenity\x12\x1d\n\x10search_radius_km\x18\n \x01(\rH\x01\x88\x01\x01\x12\"\n\x04\x62\x65\x64s\x18\x0b \x03(\x0e\x32\x14.hotel_search.v1.BedB\x14\n\x12_max_nightly_priceB\x13\n\x11_search_radius_km\"u\n\x0bUserSession\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12,\n\x0buser_device\x18\x02 \x01(\x0e\x32\x17.hotel_search.v1.Device\x12\x16\n\tmember_id\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_member_id*A\n\x06\x44\x65vice\x12\x0e\n\nMOBILE_APP\x10\x00\x12\x12\n\x0eMOBILE_BROWSER\x10\x01\x12\x13\n\x0f\x44\x45SKTOP_BROWSER\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hotel_search.v1.hotel_search_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICE']._serialized_start=722
  _globals['_DEVICE']._serialized_end=787
  _globals['_HOTELSEARCHREQUEST']._serialized_start=143
  _globals['_HOTELSEARCHREQUEST']._serialized_end=601
  _globals['_USERSESSION']._serialized_start=603
  _globals['_USERSESSION']._serialized_end=720
# @@protoc_insertion_point(module_scope)
